# Generated by Django 5.1.6 on 2025-02-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleto',
            name='pago',
        ),
        migrations.AddField(
            model_name='boleto',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='boletos/'),
        ),
        migrations.AlterField(
            model_name='boleto',
            name='status',
            field=models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente'), ('vencido', 'Vencido')], max_length=20),
        ),
    ]
