# Generated by Django 5.1.6 on 2025-02-17 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0002_remove_boleto_pago_boleto_arquivo_and_more'),
    ]

    operations = [
    ]
