# Generated by Django 5.1.6 on 2025-02-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0003_auto_20250216_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
