# Generated by Django 5.1.6 on 2025-03-08 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='data_envio',
        ),
    ]
