# Generated by Django 5.1.6 on 2025-02-17 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='enviado_pelo_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=10),
        ),
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(help_text='Envie apenas arquivos em PDF', upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to=settings.AUTH_USER_MODEL),
        ),
    ]
